### ISSUE TITLE
Is there any documentation about Webdriver logger wrapper?

### ISSUE THREAD

**Issue by Xotabu4** [barancev/webdriver-extensions#1]
Hi! I curious about documentation for webdriver logger wrapper. I remember presentation about it on one of Selenium Camp conferences, but it doesn't contain any examples (http://seleniumcamp.com/archive/materials-2014/web-driver-decoration/) 
Or usage in test class is enough to start work with it? (https://github.com/barancev/webdriver-extensions/blob/master/webdriver-logging-wrapper/src/test/java/ru/stqa/selenium/wrapper/LoggingWrapperTest.java)

Thanks!

**Comment by barancev** [comment]
Yes, the only documentation available at the moment is in the form of tests/samples.
