### ISSUE TITLE
problem with webdriver-factory

### ISSUE THREAD

**Issue by emaks** [barancev/webdriver-extensions#2]
If alert on page will be opened before executing `WebDriverFactory.getDriver()` we will get `UnhandledAlertException`([in this place](https://github.com/barancev/webdriver-extensions/blob/master/webdriver-factory/src/main/java/ru/stqa/selenium/factory/ThreadLocalSingletonStorage.java#L53)) and new browser ssesion wil be created

**Comment by barancev** [comment]
Fixed by commit 35f4be205ef176096b191966551472afb469776b and released to maven repository in version 1.2.49 (that depends on Selenium 2.49.1)
