### ISSUE TITLE
Close one of the windows and switch back

### ISSUE THREAD

**Issue by angavr** [barancev/webdriver-extensions#3]
When another window is open during the execution it will be possible to switch there and do all related actions. But after you are finished and the `close()` call is done, there won't be a chance to switch back to the primary page. New instance will be created on `getDriver()` as the method in `SingletonStorage` will fail to do the `getCurrentUrl()` and consider browser dead.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by barancev** [comment]
I see, getCurrentUrl is not the best way to check a browser liveness...

**Comment by angavr** [comment]
Was wondering if checking the handles and their number can make a good hint in this case. Though, this should be probably done together with something else...

Actually if this check is intended to see if driver didn't 'glitch' at some point, it will be difficult to define the generic set of actions for any situation.

**Comment by barancev** [comment]
Fixed by 109db84dd00bf2b96cfb25aa913cc71f18e17006

**Comment by angavr** [comment]
Thanks! Which maven repo version is it?

**Comment by barancev** [comment]
Version 1.1.52 is planned to this weekend.
